### ISSUE TITLE
Attempt to invoke virtual method 'java.util.List edmt.dev.androidnewsapp.Model.WebSite.getSources()' on a null object reference

### ISSUE THREAD

**Issue by Anonymousgaurav** [eddydn/EDMTNewsApp#10]
11-16 19:56:18.454 32592-32592/edmt.dev.androidnewsapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: edmt.dev.androidnewsapp, PID: 32592
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List edmt.dev.androidnewsapp.Model.WebSite.getSources()' on a null object reference
        at edmt.dev.androidnewsapp.Adapter.ListSourceAdapter.getItemCount(ListSourceAdapter.java:97)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3603)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3408)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
        at android.view.View.layout(View.java:17969)
        at android.view.ViewGroup.layout(ViewGroup.java:5721)
        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:610)
        at android.view.View.layout(View.java:17969)
        at android.view.ViewGroup.layout(ViewGroup.java:5721)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
        at android.view.View.layout(View.java:17969)
        at android.view.ViewGroup.layout(ViewGroup.java:5721)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
        at android.view.View.layout(View.java:17969)
        at android.view.ViewGroup.layout(ViewGroup.java:5721)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
        at android.view.View.layout(View.java:17969)
        at android.view.ViewGroup.layout(ViewGroup.java:5721)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
        at android.view.View.layout(View.java:17969)
        at android.view.ViewGroup.layout(ViewGroup.java:5721)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
        at android.view.View.layout(View.java:17969)
        at android.view.ViewGroup.layout(ViewGroup.java:5721)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2726)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2394)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1481)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7047)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:910)
        at android.view.Choreographer.doCallbacks(Choreographer.java:712)
        at android.view.Choreographer.doFrame(Choreographer.java:646)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:896)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6339)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)

**Comment by brownstic** [comment]
When does this crash happen?

**Comment by Anonymousgaurav** [comment]
after loading the application

**Comment by Anonymousgaurav** [comment]
after loading of application it closes automatically.
